import type { PatternData } from "./constants";

export const patterns: PatternData[] = [
  // --- BATCH 1: TRIANGLES (1-10) ---
  {
    id: "p1",
    name: "Right Triangle (Star)",
    description: "Left-aligned right triangle using a symbol",
    category: "Triangles",
    subCategory: "Right Triangle",
    patternType: "Solid",
    difficulty: "Beginner",
    group: "Star",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "i",
      valueFormula: "symbol",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p2",
    name: "Right Triangle (Col Num)",
    description: "Left-aligned right triangle showing column numbers",
    category: "Triangles",
    subCategory: "Right Triangle",
    patternType: "Solid",
    difficulty: "Beginner",
    group: "Number",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "i",
      valueFormula: "col",
    },
    config: { defaultRows: 5, symbol: "" },
  },
  {
    id: "p3",
    name: "Right Triangle (Row Num)",
    description: "Left-aligned right triangle showing row numbers",
    category: "Triangles",
    subCategory: "Right Triangle",
    patternType: "Solid",
    difficulty: "Beginner",
    group: "Number",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "i",
      valueFormula: "row",
    },
    config: { defaultRows: 5, symbol: "" },
  },
  {
    id: "p4",
    name: "Inverted Triangle",
    description: "Left-aligned inverted triangle",
    category: "Triangles",
    subCategory: "Right Triangle",
    patternType: "Solid",
    difficulty: "Beginner",
    group: "Star",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "N-i+1",
      valueFormula: "symbol",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p5",
    name: "Mirrored Right Triangle",
    description: "Right-aligned triangle using leading spaces",
    category: "Triangles",
    subCategory: "Right Triangle",
    patternType: "Mirrored",
    difficulty: "Intermediate",
    group: "Star",
    logic: {
      archetype: "LINEAR",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "i",
      valueFormula: "symbol",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p6",
    name: "Mirrored Inverted Triangle",
    description: "Right-aligned inverted triangle using leading spaces",
    category: "Triangles",
    subCategory: "Right Triangle",
    patternType: "Mirrored",
    difficulty: "Intermediate",
    group: "Star",
    logic: {
      archetype: "LINEAR",
      renderSpaces: true,
      spaceFormula: "i-1",
      fillFormula: "N-i+1",
      valueFormula: "symbol",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p7",
    name: "Alpha Triangle (A-BB)",
    description: "Alphabet triangle repeating the row letter",
    category: "Triangles",
    subCategory: "Alphabet",
    patternType: "Sequence",
    difficulty: "Beginner",
    group: "Character",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "i",
      valueFormula: "alpha-row",
    },
    config: { defaultRows: 5, symbol: "" },
  },
  {
    id: "p8",
    name: "Alpha Triangle (A-AB)",
    description: "Alphabet triangle increasing across columns",
    category: "Triangles",
    subCategory: "Alphabet",
    patternType: "Sequence",
    difficulty: "Beginner",
    group: "Character",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "i",
      valueFormula: "alpha-col",
    },
    config: { defaultRows: 5, symbol: "" },
  },
  {
    id: "p9",
    name: "Binary Triangle",
    description: "Triangle filled with alternating 0/1 values",
    category: "Triangles",
    subCategory: "Binary",
    patternType: "Sequence",
    difficulty: "Beginner",
    group: "Number",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "i",
      valueFormula: "binary",
    },
    config: { defaultRows: 5, symbol: "" },
  },
  {
    id: "p10",
    name: "Double Right Triangle",
    description: "Triangle that grows then shrinks (hourglass-like edge)",
    category: "Triangles",
    subCategory: "Right Triangle",
    patternType: "Solid",
    difficulty: "Intermediate",
    group: "Star",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "i <= N ? i : 2*N - i",
      valueFormula: "symbol",
    },
    config: { defaultRows: 6, symbol: "*" },
  },

  // --- BATCH 2: PYRAMIDS & DIAMONDS (11-20) ---
  {
    id: "p11",
    name: "Full Pyramid",
    description: "Centered pyramid with increasing odd-width rows",
    category: "Pyramids & Diamonds",
    subCategory: "Pyramid",
    patternType: "Centered",
    difficulty: "Intermediate",
    group: "Star",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "2*i-1",
      valueFormula: "symbol",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p12",
    name: "Inverted Pyramid",
    description: "Centered inverted pyramid with decreasing odd-width rows",
    category: "Pyramids & Diamonds",
    subCategory: "Pyramid",
    patternType: "Centered",
    difficulty: "Intermediate",
    group: "Star",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "i-1",
      fillFormula: "2*(N-i)+1",
      valueFormula: "symbol",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p13",
    name: "Number Pyramid",
    description: "Centered pyramid showing column numbers",
    category: "Pyramids & Diamonds",
    subCategory: "Pyramid",
    patternType: "Centered",
    difficulty: "Intermediate",
    group: "Number",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "2*i-1",
      valueFormula: "col",
    },
    config: { defaultRows: 5, symbol: "" },
  },
  {
    id: "p14",
    name: "Hollow Pyramid",
    description: "Pyramid outline using a hollow condition",
    category: "Pyramids & Diamonds",
    subCategory: "Pyramid",
    patternType: "Hollow",
    difficulty: "Advanced",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "2*i-1",
      valueFormula: "symbol",
      condition: "j==1 || j==2*i-1 || i==N",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p15",
    name: "Diamond",
    description: "Symmetric diamond shape",
    category: "Pyramids & Diamonds",
    subCategory: "Diamond",
    patternType: "Centered",
    difficulty: "Advanced",
    group: "Star",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "i <= Math.ceil(N/2) ? Math.ceil(N/2)-i : i-Math.ceil(N/2)",
      fillFormula: "i <= Math.ceil(N/2) ? 2*i-1 : 2*(N-i)+1",
      valueFormula: "symbol",
    },
    config: { defaultRows: 7, symbol: "*" },
  },
  {
    id: "p16",
    name: "Alpha Pyramid",
    description: "Centered alphabet pyramid",
    category: "Pyramids & Diamonds",
    subCategory: "Pyramid",
    patternType: "Sequence",
    difficulty: "Intermediate",
    group: "Character",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "2*i-1",
      valueFormula: "alpha-col",
    },
    config: { defaultRows: 5, symbol: "" },
  },
  {
    id: "p17",
    name: "Gapped Pyramid",
    description: "Pyramid with spaced-out symbols",
    category: "Pyramids & Diamonds",
    subCategory: "Pyramid",
    patternType: "Centered",
    difficulty: "Intermediate",
    group: "Star",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "i",
      valueFormula: "symbol",
    },
    config: { defaultRows: 5, symbol: "* " },
  },
  {
    id: "p18",
    name: "Hourglass",
    description: "Hourglass shape (increasing then decreasing inner width)",
    category: "Pyramids & Diamonds",
    subCategory: "Hourglass",
    patternType: "Centered",
    difficulty: "Advanced",
    group: "Star",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "i <= N/2 ? i-1 : N-i",
      fillFormula: "i <= N/2 ? N-2*i+2 : 2*i-N",
      valueFormula: "symbol",
    },
    config: { defaultRows: 6, symbol: "*" },
  },
  {
    id: "p19",
    name: "Right Side Pyramid",
    description: "Single-side pyramid (grows then shrinks)",
    category: "Triangles",
    subCategory: "Single Side",
    patternType: "Solid",
    difficulty: "Intermediate",
    group: "Star",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "i <= N/2 ? i : N-i+1",
      valueFormula: "symbol",
    },
    config: { defaultRows: 6, symbol: "*" },
  },
  {
    id: "p20",
    name: "Palindromic Pyramid",
    description: "Centered numeric palindromes per row (1..i..1)",
    category: "Math & Sequences",
    subCategory: "Palindrome",
    patternType: "Sequence",
    difficulty: "Expert",
    group: "Number",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "2*i-1",
      valueFormula: "palindrome",
    },
    config: { defaultRows: 5, symbol: "" },
  },

  // --- BATCH 3: HOLLOW & GRIDS (21-35) ---
  {
    id: "p21",
    name: "Solid Square",
    description: "Filled square",
    category: "Grids & Squares",
    subCategory: "Square",
    patternType: "Solid",
    difficulty: "Beginner",
    group: "Star",
    logic: {
      archetype: "STATIC",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "symbol",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p22",
    name: "Hollow Square",
    description: "Square outline",
    category: "Grids & Squares",
    subCategory: "Square",
    patternType: "Hollow",
    difficulty: "Intermediate",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "i==1 || i==N || j==1 || j==N",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p23",
    name: "Hollow Square Diagonal",
    description: "Square outline with both diagonals",
    category: "Grids & Squares",
    subCategory: "Square",
    patternType: "Outline",
    difficulty: "Advanced",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "i==1 || i==N || j==1 || j==N || i==j || j==N-i+1",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p24",
    name: "X-Pattern",
    description: "X shape using diagonals",
    category: "Grids & Squares",
    subCategory: "Crosses",
    patternType: "Outline",
    difficulty: "Intermediate",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "i==j || j==N-i+1",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p25",
    name: "Plus Pattern",
    description: "Plus sign centered in a grid",
    category: "Grids & Squares",
    subCategory: "Crosses",
    patternType: "Outline",
    difficulty: "Intermediate",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "i==Math.ceil(N/2) || j==Math.ceil(N/2)",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p26",
    name: "Rhombus",
    description: "Slanted square (parallelogram)",
    category: "Grids & Squares",
    subCategory: "Rhombus",
    patternType: "Solid",
    difficulty: "Intermediate",
    group: "Star",
    logic: {
      archetype: "STATIC",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "N",
      valueFormula: "symbol",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p27",
    name: "Hollow Rhombus",
    description: "Rhombus outline",
    category: "Grids & Squares",
    subCategory: "Rhombus",
    patternType: "Hollow",
    difficulty: "Advanced",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "i==1 || i==N || j==1 || j==N",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p28",
    name: "Z-Pattern",
    description: "Z shape in a grid",
    category: "Grids & Squares",
    subCategory: "Letters",
    patternType: "Outline",
    difficulty: "Intermediate",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "i==1 || i==N || j==N-i+1",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p29",
    name: "Checkerboard",
    description: "Alternating 0/1 checkerboard",
    category: "Grids & Squares",
    subCategory: "Grid",
    patternType: "Sequence",
    difficulty: "Intermediate",
    group: "Number",
    logic: {
      archetype: "STATIC",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "binary",
    },
    config: { defaultRows: 5, symbol: "" },
  },
  {
    id: "p30",
    name: "Parallel Lines",
    description: "Two vertical border lines",
    category: "Grids & Squares",
    subCategory: "Lines",
    patternType: "Outline",
    difficulty: "Beginner",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "j==1 || j==N",
    },
    config: { defaultRows: 5, symbol: "*" },
  },

  // --- BATCH 4: ADVANCED MATH & SHAPES (31-50) ---
  {
    id: "p31",
    name: "Floyd's Triangle",
    description: "Floyd's triangle using a running counter",
    category: "Math & Sequences",
    subCategory: "Floyd",
    patternType: "Sequence",
    difficulty: "Advanced",
    group: "Number",
    logic: {
      archetype: "MATH_SEQ",
      renderSpaces: false,
      fillFormula: "i",
      valueFormula: "counter",
    },
    config: { defaultRows: 5, symbol: "" },
  },
  {
    id: "p32",
    name: "Butterfly Pattern",
    description: "Butterfly wings pattern",
    category: "Misc",
    subCategory: "Butterfly",
    patternType: "Outline",
    difficulty: "Expert",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "2*N",
      valueFormula: "symbol",
      condition: "j<=i || j>2*N-i",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p33",
    name: "Pascal's Triangle",
    description: "Pascal's triangle values",
    category: "Math & Sequences",
    subCategory: "Pascal",
    patternType: "Sequence",
    difficulty: "Expert",
    group: "Number",
    logic: {
      archetype: "MATH_SEQ",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "i",
      valueFormula: "pascal",
    },
    config: { defaultRows: 5, symbol: "" },
  },
  {
    id: "p34",
    name: "Left Arrow",
    description: "Arrow-like shape using leading spaces",
    category: "Misc",
    subCategory: "Arrows",
    patternType: "Outline",
    difficulty: "Advanced",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: true,
      spaceFormula: "i <= N ? N-i : i-N",
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "j==1",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p35",
    name: "Hollow Diamond",
    description: "Diamond outline",
    category: "Pyramids & Diamonds",
    subCategory: "Diamond",
    patternType: "Hollow",
    difficulty: "Expert",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: true,
      spaceFormula: "i <= Math.ceil(N/2) ? Math.ceil(N/2)-i : i-Math.ceil(N/2)",
      fillFormula: "i <= Math.ceil(N/2) ? 2*i-1 : 2*(N-i)+1",
      valueFormula: "symbol",
      condition: "j==1 || j==(i <= Math.ceil(N/2) ? 2*i-1 : 2*(N-i)+1)",
    },
    config: { defaultRows: 7, symbol: "*" },
  },
  // ... (Continue the pattern by varying Row vs Col for the remaining 15 items)
  {
    id: "p36",
    name: "Col Binary Triangle",
    description: "Triangle using binary value based on column parity",
    category: "Triangles",
    subCategory: "Binary",
    patternType: "Sequence",
    difficulty: "Beginner",
    group: "Number",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "i",
      valueFormula: "binary-col",
    },
    config: { defaultRows: 5, symbol: "" },
  },

  {
    id: "p37",
    name: "Row Binary Triangle",
    description: "Triangle using binary value based on row parity",
    category: "Triangles",
    subCategory: "Binary",
    patternType: "Sequence",
    difficulty: "Beginner",
    group: "Number",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "i",
      valueFormula: "binary-row",
    },
    config: { defaultRows: 5, symbol: "" },
  },
  {
    id: "p38",
    name: "Right Triangle (Alternating 0/1)",
    description: "Left-aligned triangle with alternating binary values",
    category: "Triangles",
    subCategory: "Binary",
    patternType: "Sequence",
    difficulty: "Intermediate",
    group: "Number",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "i",
      valueFormula: "binary",
    },
    config: { defaultRows: 6, symbol: "" },
  },
  {
    id: "p39",
    name: "Mirrored Number Triangle (Row Num)",
    description: "Right-aligned triangle showing row numbers",
    category: "Triangles",
    subCategory: "Right Triangle",
    patternType: "Mirrored",
    difficulty: "Intermediate",
    group: "Number",
    logic: {
      archetype: "LINEAR",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "i",
      valueFormula: "row",
    },
    config: { defaultRows: 5, symbol: "" },
  },
  {
    id: "p40",
    name: "Mirrored Number Triangle (Col Num)",
    description: "Right-aligned triangle showing column numbers",
    category: "Triangles",
    subCategory: "Right Triangle",
    patternType: "Mirrored",
    difficulty: "Intermediate",
    group: "Number",
    logic: {
      archetype: "LINEAR",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "i",
      valueFormula: "col",
    },
    config: { defaultRows: 5, symbol: "" },
  },
  {
    id: "p41",
    name: "Alpha Right Triangle (A-AB)",
    description: "Left-aligned triangle increasing alphabet across columns",
    category: "Triangles",
    subCategory: "Alphabet",
    patternType: "Sequence",
    difficulty: "Beginner",
    group: "Character",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "i",
      valueFormula: "alpha-col",
    },
    config: { defaultRows: 6, symbol: "" },
  },
  {
    id: "p42",
    name: "Alpha Right Triangle (A-BB)",
    description: "Left-aligned triangle repeating alphabet based on row",
    category: "Triangles",
    subCategory: "Alphabet",
    patternType: "Sequence",
    difficulty: "Beginner",
    group: "Character",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "i",
      valueFormula: "alpha-row",
    },
    config: { defaultRows: 6, symbol: "" },
  },
  {
    id: "p43",
    name: "Inverted Alpha Triangle",
    description: "Inverted triangle repeating alphabet based on row",
    category: "Triangles",
    subCategory: "Alphabet",
    patternType: "Sequence",
    difficulty: "Intermediate",
    group: "Character",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "N-i+1",
      valueFormula: "alpha-row",
    },
    config: { defaultRows: 6, symbol: "" },
  },
  {
    id: "p44",
    name: "Inverted Binary Triangle",
    description: "Inverted triangle using binary value",
    category: "Triangles",
    subCategory: "Binary",
    patternType: "Sequence",
    difficulty: "Intermediate",
    group: "Number",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "N-i+1",
      valueFormula: "binary",
    },
    config: { defaultRows: 6, symbol: "" },
  },
  {
    id: "p45",
    name: "Centered Number Pyramid (Row Num)",
    description: "Centered pyramid showing row numbers",
    category: "Pyramids & Diamonds",
    subCategory: "Pyramid",
    patternType: "Centered",
    difficulty: "Intermediate",
    group: "Number",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "2*i-1",
      valueFormula: "row",
    },
    config: { defaultRows: 5, symbol: "" },
  },
  {
    id: "p46",
    name: "Centered Number Pyramid (Col Num)",
    description: "Centered pyramid showing column numbers",
    category: "Pyramids & Diamonds",
    subCategory: "Pyramid",
    patternType: "Centered",
    difficulty: "Intermediate",
    group: "Number",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "2*i-1",
      valueFormula: "col",
    },
    config: { defaultRows: 5, symbol: "" },
  },
  {
    id: "p47",
    name: "Hollow Inverted Pyramid",
    description: "Inverted pyramid outline",
    category: "Pyramids & Diamonds",
    subCategory: "Pyramid",
    patternType: "Hollow",
    difficulty: "Advanced",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: true,
      spaceFormula: "i-1",
      fillFormula: "2*(N-i)+1",
      valueFormula: "symbol",
      condition: "j==1 || j==2*(N-i)+1 || i==1",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p48",
    name: "Centered Binary Pyramid",
    description: "Centered pyramid using binary values",
    category: "Pyramids & Diamonds",
    subCategory: "Pyramid",
    patternType: "Sequence",
    difficulty: "Advanced",
    group: "Number",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "2*i-1",
      valueFormula: "binary",
    },
    config: { defaultRows: 6, symbol: "" },
  },
  {
    id: "p49",
    name: "Centered Alpha Pyramid (Row)",
    description: "Centered pyramid repeating alphabet based on row",
    category: "Pyramids & Diamonds",
    subCategory: "Pyramid",
    patternType: "Sequence",
    difficulty: "Intermediate",
    group: "Character",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "2*i-1",
      valueFormula: "alpha-row",
    },
    config: { defaultRows: 5, symbol: "" },
  },

  {
    id: "p51",
    name: "Solid Rectangle",
    description: "Filled rectangle (rows x cols) using a static width",
    category: "Grids & Squares",
    subCategory: "Grid",
    patternType: "Solid",
    difficulty: "Beginner",
    group: "Star",
    logic: {
      archetype: "STATIC",
      renderSpaces: false,
      fillFormula: "N+2",
      valueFormula: "symbol",
    },
    config: { defaultRows: 5, symbol: "*" },
  },
  {
    id: "p52",
    name: "Hollow Rectangle",
    description: "Rectangle outline (rows x cols) using a static width",
    category: "Grids & Squares",
    subCategory: "Grid",
    patternType: "Hollow",
    difficulty: "Intermediate",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N+2",
      valueFormula: "symbol",
      condition: "i==1 || i==N || j==1 || j==N+2",
    },
    config: { defaultRows: 6, symbol: "*" },
  },
  {
    id: "p53",
    name: "Grid Row Numbers",
    description: "Grid filled with row numbers",
    category: "Grids & Squares",
    subCategory: "Grid",
    patternType: "Sequence",
    difficulty: "Beginner",
    group: "Number",
    logic: {
      archetype: "STATIC",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "row",
    },
    config: { defaultRows: 6, symbol: "" },
  },
  {
    id: "p54",
    name: "Grid Col Numbers",
    description: "Grid filled with column numbers",
    category: "Grids & Squares",
    subCategory: "Grid",
    patternType: "Sequence",
    difficulty: "Beginner",
    group: "Number",
    logic: {
      archetype: "STATIC",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "col",
    },
    config: { defaultRows: 6, symbol: "" },
  },
  {
    id: "p55",
    name: "Border Only",
    description: "Only border of a square grid",
    category: "Grids & Squares",
    subCategory: "Lines",
    patternType: "Outline",
    difficulty: "Beginner",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "i==1 || i==N || j==1 || j==N",
    },
    config: { defaultRows: 7, symbol: "#" },
  },
  {
    id: "p56",
    name: "Diagonal Only",
    description: "Main diagonal in a grid",
    category: "Grids & Squares",
    subCategory: "Lines",
    patternType: "Outline",
    difficulty: "Beginner",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "i==j",
    },
    config: { defaultRows: 7, symbol: "*" },
  },
  {
    id: "p57",
    name: "Anti Diagonal Only",
    description: "Secondary diagonal in a grid",
    category: "Grids & Squares",
    subCategory: "Lines",
    patternType: "Outline",
    difficulty: "Beginner",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "j==N-i+1",
    },
    config: { defaultRows: 7, symbol: "*" },
  },
  {
    id: "p58",
    name: "Grid Cross",
    description: "Both diagonals and the center cross",
    category: "Grids & Squares",
    subCategory: "Crosses",
    patternType: "Outline",
    difficulty: "Advanced",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "i==j || j==N-i+1 || i==Math.ceil(N/2) || j==Math.ceil(N/2)",
    },
    config: { defaultRows: 9, symbol: "+" },
  },
  {
    id: "p59",
    name: "Checkerboard (Symbol)",
    description: "Checkerboard using a symbol and blanks",
    category: "Grids & Squares",
    subCategory: "Grid",
    patternType: "Outline",
    difficulty: "Intermediate",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: true,
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "(i+j)%2==0",
    },
    config: { defaultRows: 8, symbol: "*" },
  },
  {
    id: "p60",
    name: "Binary Grid",
    description: "Grid filled with alternating 0/1",
    category: "Grids & Squares",
    subCategory: "Grid",
    patternType: "Sequence",
    difficulty: "Intermediate",
    group: "Number",
    logic: {
      archetype: "STATIC",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "binary",
    },
    config: { defaultRows: 8, symbol: "" },
  },
  {
    id: "p61",
    name: "Frame With X",
    description: "Square border with X diagonals",
    category: "Grids & Squares",
    subCategory: "Square",
    patternType: "Outline",
    difficulty: "Advanced",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "i==1 || i==N || j==1 || j==N || i==j || j==N-i+1",
    },
    config: { defaultRows: 9, symbol: "*" },
  },
  {
    id: "p62",
    name: "Hollow Right Triangle",
    description: "Triangle outline (two legs + hypotenuse)",
    category: "Triangles",
    subCategory: "Right Triangle",
    patternType: "Hollow",
    difficulty: "Advanced",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "i",
      valueFormula: "symbol",
      condition: "i==N || j==1 || j==i",
    },
    config: { defaultRows: 7, symbol: "*" },
  },
  {
    id: "p63",
    name: "Hollow Mirrored Triangle",
    description: "Right-aligned hollow triangle",
    category: "Triangles",
    subCategory: "Right Triangle",
    patternType: "Mirrored",
    difficulty: "Advanced",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "i",
      valueFormula: "symbol",
      condition: "i==N || j==1 || j==i",
    },
    config: { defaultRows: 7, symbol: "*" },
  },
  {
    id: "p64",
    name: "Hollow Pyramid (Outline)",
    description: "Centered pyramid outline",
    category: "Pyramids & Diamonds",
    subCategory: "Pyramid",
    patternType: "Hollow",
    difficulty: "Advanced",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "2*i-1",
      valueFormula: "symbol",
      condition: "j==1 || j==2*i-1 || i==N",
    },
    config: { defaultRows: 6, symbol: "*" },
  },
  {
    id: "p65",
    name: "Hollow Diamond (Full)",
    description: "Diamond outline with symmetric halves",
    category: "Pyramids & Diamonds",
    subCategory: "Diamond",
    patternType: "Hollow",
    difficulty: "Expert",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: true,
      spaceFormula: "i <= Math.ceil(N/2) ? Math.ceil(N/2)-i : i-Math.ceil(N/2)",
      fillFormula: "i <= Math.ceil(N/2) ? 2*i-1 : 2*(N-i)+1",
      valueFormula: "symbol",
      condition: "j==1 || j==(i <= Math.ceil(N/2) ? 2*i-1 : 2*(N-i)+1)",
    },
    config: { defaultRows: 9, symbol: "*" },
  },
  {
    id: "p66",
    name: "Solid Diamond (Symbol)",
    description: "Solid diamond using a symbol",
    category: "Pyramids & Diamonds",
    subCategory: "Diamond",
    patternType: "Centered",
    difficulty: "Advanced",
    group: "Star",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "i <= Math.ceil(N/2) ? Math.ceil(N/2)-i : i-Math.ceil(N/2)",
      fillFormula: "i <= Math.ceil(N/2) ? 2*i-1 : 2*(N-i)+1",
      valueFormula: "symbol",
    },
    config: { defaultRows: 9, symbol: "*" },
  },
  {
    id: "p67",
    name: "Diamond (Binary)",
    description: "Diamond filled with binary values",
    category: "Pyramids & Diamonds",
    subCategory: "Diamond",
    patternType: "Sequence",
    difficulty: "Expert",
    group: "Number",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "i <= Math.ceil(N/2) ? Math.ceil(N/2)-i : i-Math.ceil(N/2)",
      fillFormula: "i <= Math.ceil(N/2) ? 2*i-1 : 2*(N-i)+1",
      valueFormula: "binary",
    },
    config: { defaultRows: 9, symbol: "" },
  },
  {
    id: "p68",
    name: "Diamond (Alpha Col)",
    description: "Diamond filled with alphabet sequence across columns",
    category: "Pyramids & Diamonds",
    subCategory: "Diamond",
    patternType: "Sequence",
    difficulty: "Expert",
    group: "Character",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "i <= Math.ceil(N/2) ? Math.ceil(N/2)-i : i-Math.ceil(N/2)",
      fillFormula: "i <= Math.ceil(N/2) ? 2*i-1 : 2*(N-i)+1",
      valueFormula: "alpha-col",
    },
    config: { defaultRows: 9, symbol: "" },
  },
  {
    id: "p69",
    name: "Hourglass (Hollow)",
    description: "Hourglass outline",
    category: "Pyramids & Diamonds",
    subCategory: "Hourglass",
    patternType: "Hollow",
    difficulty: "Expert",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: true,
      spaceFormula: "i <= N/2 ? i-1 : N-i",
      fillFormula: "i <= N/2 ? N-2*i+2 : 2*i-N",
      valueFormula: "symbol",
      condition: "j==1 || j==(i <= N/2 ? N-2*i+2 : 2*i-N)",
    },
    config: { defaultRows: 8, symbol: "*" },
  },
  {
    id: "p70",
    name: "Pascal's Triangle (Compact)",
    description: "Pascal's triangle without leading spaces",
    category: "Math & Sequences",
    subCategory: "Pascal",
    patternType: "Sequence",
    difficulty: "Expert",
    group: "Number",
    logic: {
      archetype: "MATH_SEQ",
      renderSpaces: false,
      fillFormula: "i",
      valueFormula: "pascal",
    },
    config: { defaultRows: 7, symbol: "" },
  },
  {
    id: "p71",
    name: "Floyd's Triangle (Wider)",
    description: "Floyd's triangle with more rows",
    category: "Math & Sequences",
    subCategory: "Floyd",
    patternType: "Sequence",
    difficulty: "Advanced",
    group: "Number",
    logic: {
      archetype: "MATH_SEQ",
      renderSpaces: false,
      fillFormula: "i",
      valueFormula: "counter",
    },
    config: { defaultRows: 8, symbol: "" },
  },
  {
    id: "p72",
    name: "Palindromic Pyramid (Outline)",
    description: "Palindromic pyramid but only on border positions",
    category: "Math & Sequences",
    subCategory: "Palindrome",
    patternType: "Outline",
    difficulty: "Expert",
    group: "Number",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "2*i-1",
      valueFormula: "palindrome",
      condition: "j==1 || j==2*i-1 || i==N",
    },
    config: { defaultRows: 6, symbol: "" },
  },
  {
    id: "p73",
    name: "Solid Square (Row Num)",
    description: "Filled square showing row numbers",
    category: "Grids & Squares",
    subCategory: "Square",
    patternType: "Sequence",
    difficulty: "Beginner",
    group: "Number",
    logic: {
      archetype: "STATIC",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "row",
    },
    config: { defaultRows: 6, symbol: "" },
  },
  {
    id: "p74",
    name: "Solid Square (Col Num)",
    description: "Filled square showing column numbers",
    category: "Grids & Squares",
    subCategory: "Square",
    patternType: "Sequence",
    difficulty: "Beginner",
    group: "Number",
    logic: {
      archetype: "STATIC",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "col",
    },
    config: { defaultRows: 6, symbol: "" },
  },
  {
    id: "p75",
    name: "Hollow Square (Binary)",
    description: "Square outline filled with binary values",
    category: "Grids & Squares",
    subCategory: "Square",
    patternType: "Hollow",
    difficulty: "Advanced",
    group: "Number",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "binary",
      condition: "i==1 || i==N || j==1 || j==N",
    },
    config: { defaultRows: 7, symbol: "" },
  },
  {
    id: "p76",
    name: "Hollow Square (Alpha)",
    description: "Square outline filled with alphabet values",
    category: "Grids & Squares",
    subCategory: "Square",
    patternType: "Hollow",
    difficulty: "Advanced",
    group: "Character",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "alpha-col",
      condition: "i==1 || i==N || j==1 || j==N",
    },
    config: { defaultRows: 7, symbol: "" },
  },
  {
    id: "p77",
    name: "Left Arrow (Filled)",
    description: "Arrow-like filled shape using spaces",
    category: "Misc",
    subCategory: "Arrows",
    patternType: "Solid",
    difficulty: "Advanced",
    group: "Star",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "i <= Math.ceil(N/2) ? 0 : i-Math.ceil(N/2)",
      fillFormula: "i <= Math.ceil(N/2) ? Math.ceil(N/2)+i-1 : N-i+1",
      valueFormula: "symbol",
    },
    config: { defaultRows: 7, symbol: "<" },
  },
  {
    id: "p78",
    name: "Right Arrow (Outline)",
    description: "Outline arrow pointing right",
    category: "Misc",
    subCategory: "Arrows",
    patternType: "Outline",
    difficulty: "Expert",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: true,
      spaceFormula: "i <= Math.ceil(N/2) ? Math.ceil(N/2)-i : i-Math.ceil(N/2)",
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "j==N",
    },
    config: { defaultRows: 7, symbol: ">" },
  },
  {
    id: "p79",
    name: "Letter Z (Hollow)",
    description: "Z outline with border rows and diagonal",
    category: "Grids & Squares",
    subCategory: "Letters",
    patternType: "Outline",
    difficulty: "Intermediate",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "i==1 || i==N || j==N-i+1",
    },
    config: { defaultRows: 7, symbol: "Z" },
  },
  {
    id: "p80",
    name: "Letter X (Alpha)",
    description: "X shape with alphabet values",
    category: "Grids & Squares",
    subCategory: "Letters",
    patternType: "Outline",
    difficulty: "Intermediate",
    group: "Character",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "alpha-col",
      condition: "i==j || j==N-i+1",
    },
    config: { defaultRows: 7, symbol: "" },
  },
  {
    id: "p81",
    name: "Butterfly (Binary)",
    description: "Butterfly wings pattern using binary values",
    category: "Misc",
    subCategory: "Butterfly",
    patternType: "Outline",
    difficulty: "Expert",
    group: "Number",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "2*N",
      valueFormula: "binary",
      condition: "j<=i || j>2*N-i",
    },
    config: { defaultRows: 7, symbol: "" },
  },
  {
    id: "p82",
    name: "Spaced Triangle",
    description: "Triangle with spaces between symbols",
    category: "Triangles",
    subCategory: "Right Triangle",
    patternType: "Solid",
    difficulty: "Beginner",
    group: "Star",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "i",
      valueFormula: "symbol",
    },
    config: { defaultRows: 7, symbol: "* " },
  },
  {
    id: "p83",
    name: "Inverted Spaced Triangle",
    description: "Inverted triangle with spaces between symbols",
    category: "Triangles",
    subCategory: "Right Triangle",
    patternType: "Solid",
    difficulty: "Beginner",
    group: "Star",
    logic: {
      archetype: "LINEAR",
      renderSpaces: false,
      fillFormula: "N-i+1",
      valueFormula: "symbol",
    },
    config: { defaultRows: 7, symbol: "* " },
  },
  {
    id: "p84",
    name: "Centered Pyramid (Binary Col)",
    description: "Centered pyramid using binary based on column parity",
    category: "Pyramids & Diamonds",
    subCategory: "Pyramid",
    patternType: "Sequence",
    difficulty: "Advanced",
    group: "Number",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "2*i-1",
      valueFormula: "binary-col",
    },
    config: { defaultRows: 7, symbol: "" },
  },
  {
    id: "p85",
    name: "Centered Pyramid (Binary Row)",
    description: "Centered pyramid using binary based on row parity",
    category: "Pyramids & Diamonds",
    subCategory: "Pyramid",
    patternType: "Sequence",
    difficulty: "Advanced",
    group: "Number",
    logic: {
      archetype: "SYMMETRIC",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "2*i-1",
      valueFormula: "binary-row",
    },
    config: { defaultRows: 7, symbol: "" },
  },
  {
    id: "p86",
    name: "Hollow Rhombus (Diagonal)",
    description: "Rhombus outline with a diagonal",
    category: "Grids & Squares",
    subCategory: "Rhombus",
    patternType: "Outline",
    difficulty: "Expert",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: true,
      spaceFormula: "N-i",
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "i==1 || i==N || j==1 || j==N || i==j",
    },
    config: { defaultRows: 7, symbol: "*" },
  },
  {
    id: "p87",
    name: "Hollow Square (Center Dot)",
    description: "Square outline with a center marker",
    category: "Grids & Squares",
    subCategory: "Square",
    patternType: "Outline",
    difficulty: "Intermediate",
    group: "Star",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "symbol",
      condition:
        "i==1 || i==N || j==1 || j==N || (i==Math.ceil(N/2) && j==Math.ceil(N/2))",
    },
    config: { defaultRows: 7, symbol: "." },
  },
  {
    id: "p50",
    name: "Spiral Outline",
    description: "Outline grid placeholder for spiral-like patterns",
    category: "Misc",
    subCategory: "Spiral",
    patternType: "Outline",
    difficulty: "Expert",
    group: "Number",
    logic: {
      archetype: "CONDITIONAL",
      renderSpaces: false,
      fillFormula: "N",
      valueFormula: "symbol",
      condition: "i==1 || i==N || j==1 || j==N",
    },
    config: { defaultRows: 5, symbol: "S" },
  },
];
